#!/usr/bin/env python3

from random import randint

try:
  from gi.repository import GObject
except ImportError:
  import gobject as GObject
import sys
import array
from bluez_components import *
from sense_hat import SenseHat
sense = SenseHat()

class SmartLightService(Service):
    SVC_UUID = 'FF10'
    lightState = 0 #light is off

    def __init__(self, bus, index):
        Service.__init__(self, bus, index, self.SVC_UUID, True)
        self.add_characteristic(LightColourCharacteristic(bus, 0, self))
        self.add_characteristic(TemperatureCharacteristic(bus, 1, self))

class LightColourCharacteristic(Characteristic):
    CHRC_UUID = 'FF11'
    value = [0xFF,0xFF,0xFF] # initial colour for LED light (white)
    def __init__(self, bus, index, service):
        Characteristic.__init__(
                self, bus, index,
                self.CHRC_UUID,
                ['read', 'write', 'writable-auxiliaries'],
                service)
        sense.clear()
        self.add_descriptor(
                LightColourUserDescription(bus, 0, self))

    def ReadValue(self, options):
        print('LightColourCharacteristic Read: ' + repr(self.value))
        return self.value

    def WriteValue(self, value, options):
        print('LightColourCharacteristic write')
        if len(value)!=3:
            raise InvalidValueLengthException()
        sense.clear([int(value[0]),int(value[1]),int(value[2])])
        self.value = value
        print('Finished changing colour!')

class LightColourUserDescription(Descriptor):
    CUD_UUID = '2901'

    def __init__(self, bus, index, characteristic):
        self.writable = 'writable-auxiliaries' in characteristic.flags
        self.value = array.array('B', b'Smart Light Colour(RGB)')
        self.value = self.value.tolist()
        Descriptor.__init__(
                self, bus, index,
                self.CUD_UUID,
                ['read', 'write'],
                characteristic)

    def ReadValue(self, options):
        return self.value

    def WriteValue(self, value, options):
        if not self.writable:
            raise NotPermittedException()
        self.value = value

class TemperatureService(Service):
    
    BATTERY_UUID = '180f'

    def __init__(self, bus, index):
        Service.__init__(self, bus, index, self.BATTERY_UUID, True)
        self.add_characteristic(TemperatureCharacteristic(bus, 0, self))


class TemperatureCharacteristic(Characteristic):
    temp_UUID = '2a19'

    def __init__(self, bus, index, service):
        Characteristic.__init__(
                self, bus, index,
                self.temp_UUID,
                ['read', 'notify'],
                service)
        self.notifying = False
        self.get_temp

    def notify_temp(self):
        if not self.notifying:
            return
        self.PropertiesChanged(
                GATT_CHRC_IFACE,
                                { 'Value': [dbus.Byte(self.temp)] }, [])

    def get_temp(self):
        if not self.notifying:
            return True
        
        self.temp = sense.get_temperature()
        print('Temp: ' + repr(self.temp))
        self.notify_temp()
        return True

    def ReadValue(self, options):
        print('Battery Level read: ' + repr(self.temp))
        return [dbus.Byte(self.temp)]

    def StartNotify(self):
        if self.notifying:
            print('Already notifying, nothing to do')
            return
        self.notifying = True
        self.notify_temp()

    def StopNotify(self):
        if not self.notifying:
            print('Not notifying, nothing to do')
            return

        self.notifying = False





def main():
    global mainloop

    dbus.mainloop.glib.DBusGMainLoop(set_as_default=True)

    bus = dbus.SystemBus()

    adapter = find_adapter(bus)
    if not adapter:
        print('GattManager1 interface not found')
        return

    service_manager = dbus.Interface(
            bus.get_object(BLUEZ_SERVICE_NAME, adapter),
            GATT_MANAGER_IFACE)

    app = Application(bus)
    app.add_service(SmartLightService(bus, 0))
    mainloop = GObject.MainLoop()

    print('Registering GATT application...')

    service_manager.RegisterApplication(app.get_path(), {},
                                    reply_handler=register_app_cb,
                                    error_handler=register_app_error_cb)

    mainloop.run()

if __name__ == '__main__':
    main()
